/** Kit-owned permission rules the SoT no longer ships.
 *
 * `mergeSettings` unions the deployed arrays with the SoT arrays, so dropping a
 * rule from `SoT/.claude/settings.json` never removes it from a file an earlier
 * sync already wrote. `claudeSync.ts syncRemovals` force-prunes this exact-string
 * inventory on every host so the retirement reaches existing installations
 * without `--reconcile`.
 *
 * `allow` holds the shell pre-approvals retired in favour of Claude Code's own
 * read-only command analysis and the auto-mode classifier, plus `WebFetch`.
 * `deny` holds the malformed single-backslash spellings superseded by their
 * escaped `\\)` forms; Claude Code refuses to parse the old text.
 *
 * Exact strings only. A user-authored rule outside this list survives the prune.
 */
export const RETIRED_PERMISSION_RULES = {
  allow: [
    "Bash(git *)",
    "Bash(git add *)",
    "Bash(git commit *)",
    "Bash(git status *)",
    "Bash(git diff *)",
    "Bash(git log *)",
    "Bash(git branch *)",
    "Bash(git checkout *)",
    "Bash(git switch *)",
    "Bash(git stash *)",
    "Bash(git fetch *)",
    "Bash(git pull *)",
    "Bash(git tag *)",
    "Bash(git show *)",
    "Bash(git blame *)",
    "Bash(git worktree *)",
    "Bash(gh *)",
    "Bash(pnpm *)",
    "Bash(npm *)",
    "Bash(npx *)",
    "Bash(node *)",
    "Bash(docker *)",
    "Bash(docker-compose *)",
    "Bash(ls *)",
    "Bash(cat *)",
    "Bash(find *)",
    "Bash(grep *)",
    "Bash(head *)",
    "Bash(tail *)",
    "Bash(wc *)",
    "Bash(sort *)",
    "Bash(uniq *)",
    "Bash(diff *)",
    "Bash(which *)",
    "Bash(pwd *)",
    "Bash(date *)",
    "Bash(mkdir *)",
    "Bash(basename *)",
    "Bash(dirname *)",
    "Bash(realpath *)",
    "Bash(jq *)",
    "Bash(curl *)",
    "Bash(tree *)",
    "Bash(sed *)",
    "Bash(awk *)",
    "Bash(cut *)",
    "Bash(tr *)",
    "Bash(tee *)",
    "Bash(echo *)",
    "Bash(printf *)",
    "Bash(env *)",
    "Bash(printenv *)",
    "Bash(uname *)",
    "Bash(file *)",
    "Bash(stat *)",
    "Bash(du *)",
    "Bash(id *)",
    "Bash(whoami *)",
    "Bash(php *)",
    "Bash(composer *)",
    "Bash(python3 *)",
    "Bash(python *)",
    "Bash(pip *)",
    "Bash(pip3 *)",
    "PowerShell(git *)",
    "PowerShell(git add *)",
    "PowerShell(git commit *)",
    "PowerShell(git status *)",
    "PowerShell(git diff *)",
    "PowerShell(git log *)",
    "PowerShell(git branch *)",
    "PowerShell(git checkout *)",
    "PowerShell(git switch *)",
    "PowerShell(git stash *)",
    "PowerShell(git fetch *)",
    "PowerShell(git pull *)",
    "PowerShell(git tag *)",
    "PowerShell(git show *)",
    "PowerShell(git blame *)",
    "PowerShell(git worktree *)",
    "PowerShell(gh *)",
    "PowerShell(pnpm *)",
    "PowerShell(npm *)",
    "PowerShell(npx *)",
    "PowerShell(node *)",
    "PowerShell(docker *)",
    "PowerShell(docker-compose *)",
    "PowerShell(ls *)",
    "PowerShell(cat *)",
    "PowerShell(find *)",
    "PowerShell(grep *)",
    "PowerShell(head *)",
    "PowerShell(tail *)",
    "PowerShell(wc *)",
    "PowerShell(sort *)",
    "PowerShell(uniq *)",
    "PowerShell(diff *)",
    "PowerShell(which *)",
    "PowerShell(pwd *)",
    "PowerShell(date *)",
    "PowerShell(mkdir *)",
    "PowerShell(basename *)",
    "PowerShell(dirname *)",
    "PowerShell(realpath *)",
    "PowerShell(jq *)",
    "PowerShell(curl *)",
    "PowerShell(tree *)",
    "PowerShell(sed *)",
    "PowerShell(awk *)",
    "PowerShell(cut *)",
    "PowerShell(tr *)",
    "PowerShell(tee *)",
    "PowerShell(echo *)",
    "PowerShell(printf *)",
    "PowerShell(env *)",
    "PowerShell(printenv *)",
    "PowerShell(uname *)",
    "PowerShell(file *)",
    "PowerShell(stat *)",
    "PowerShell(du *)",
    "PowerShell(id *)",
    "PowerShell(whoami *)",
    "PowerShell(php *)",
    "PowerShell(composer *)",
    "PowerShell(python3 *)",
    "PowerShell(python *)",
    "PowerShell(pip *)",
    "PowerShell(pip3 *)",
    "WebFetch"
  ],
  deny: [
    "PowerShell(Remove-Item *-Recurse* \\)",
    "PowerShell(Remove-Item *-Recurse* *:\\)",
    "PowerShell(del *-Recurse* \\)",
    "PowerShell(del *-Recurse* *:\\)",
    "PowerShell(erase *-Recurse* \\)",
    "PowerShell(erase *-Recurse* *:\\)",
    "PowerShell(rd *-Recurse* \\)",
    "PowerShell(rd *-Recurse* *:\\)",
    "PowerShell(ri *-Recurse* \\)",
    "PowerShell(ri *-Recurse* *:\\)",
    "PowerShell(rm *-Recurse* \\)",
    "PowerShell(rm *-Recurse* *:\\)",
    "PowerShell(rmdir *-Recurse* \\)",
    "PowerShell(rmdir *-Recurse* *:\\)"
  ],
  ask: []
} as const satisfies Readonly<Record<"allow" | "deny" | "ask", ReadonlyArray<string>>>
