import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { dirname, join, relative, resolve, sep } from "node:path"

export const TEXT_PAYLOAD_PATHS = [
  "SoT/.agents/skills.txt",
  "SoT/models.json",
  "SoT/toolchain.json",
  "SoT/.claude/CLAUDE.md",
  "SoT/.claude/mcp-servers.json",
  "SoT/.claude/settings.json",
  "SoT/.claude/bin/statusline.mjs",
  "SoT/.claude/bin/session-start.mjs",
  "SoT/.claude/bin/notify.mjs",
  "SoT/.codex/AGENTS.md",
  "SoT/.codex/config.toml",
  "SoT/.codex/plugins/marketplace.json",
  "SoT/.codex/rules/docks.rules"
] as const

export const BINARY_PAYLOAD_PATHS = ["notification.mp3"] as const
export const PAYLOAD_PATHS = [...TEXT_PAYLOAD_PATHS, ...BINARY_PAYLOAD_PATHS] as const

export const AUTHORING_EXCLUSIONS = [
  "SoT/.codex/agents/.gitkeep"
] as const

const GENERATED_MODULE = "cli/src/generated/sotPayload.ts"
const LAUNCHER = "docks-kit"
const BUN_PIN_START = "# BEGIN GENERATED BUN PIN"
const BUN_PIN_END = "# END GENERATED BUN PIN"

function repoPath(root: string, path: string): string {
  return join(root, ...path.split("/"))
}

function payloadHash(root: string): string {
  const hash = createHash("sha256")
  for (const path of PAYLOAD_PATHS) {
    hash.update(path)
    hash.update("\0")
    hash.update(readFileSync(repoPath(root, path)))
    hash.update("\0")
  }
  return hash.digest("hex")
}

function packageVersion(root: string): string {
  const manifest = JSON.parse(readFileSync(repoPath(root, "package.json"), "utf8")) as {
    version?: unknown
  }
  if (typeof manifest.version !== "string" || manifest.version === "") {
    throw new Error("package.json has no valid version")
  }
  return manifest.version
}

function generatedModule(root: string): string {
  const textEntries = TEXT_PAYLOAD_PATHS.map(
    (path) => `  ${JSON.stringify(path)}: ${JSON.stringify(readFileSync(repoPath(root, path), "utf8"))}`
  ).join(",\n")
  const binaryEntries = BINARY_PAYLOAD_PATHS.map(
    (path) => `  ${JSON.stringify(path)}: ${JSON.stringify(readFileSync(repoPath(root, path)).toString("base64"))}`
  ).join(",\n")
  const paths = PAYLOAD_PATHS.map((path) => `  ${JSON.stringify(path)}`).join(",\n")

  return `// Generated by cli/scripts/generate-sot-payload.ts. DO NOT EDIT.\n` +
    `// Edit SoT/, notification.mp3, or package.json, then run: bun cli/scripts/generate-sot-payload.ts\n\n` +
    `export const GENERATED_PACKAGE_VERSION = ${JSON.stringify(packageVersion(root))}\n\n` +
    `export const GENERATED_PAYLOAD_TEXT = {\n${textEntries}\n} as const\n\n` +
    `export const GENERATED_PAYLOAD_BASE64 = {\n${binaryEntries}\n} as const\n\n` +
    `export const GENERATED_PAYLOAD_PATHS = [\n${paths}\n] as const\n\n` +
    `export const GENERATED_PAYLOAD_HASH = ${JSON.stringify(payloadHash(root))}\n`
}

function verifiedBunVersion(root: string): string {
  const manifest = JSON.parse(readFileSync(repoPath(root, "SoT/toolchain.json"), "utf8")) as {
    tools?: { bun?: { verified?: unknown } }
  }
  const verified = manifest.tools?.bun?.verified
  if (typeof verified !== "string" || verified === "") {
    throw new Error("SoT/toolchain.json has no verified Bun version")
  }
  return verified
}

function generatedLauncher(root: string): string {
  const path = repoPath(root, LAUNCHER)
  const launcher = readFileSync(path, "utf8")
  const start = launcher.indexOf(BUN_PIN_START)
  const end = launcher.indexOf(BUN_PIN_END)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`docks-kit is missing the ${BUN_PIN_START}/${BUN_PIN_END} markers`)
  }
  const replacement = `${BUN_PIN_START}\nBUN_PIN=${JSON.stringify(verifiedBunVersion(root))}\n${BUN_PIN_END}`
  return launcher.slice(0, start) + replacement + launcher.slice(end + BUN_PIN_END.length)
}

function walkFiles(root: string, dir: string, output: Array<string>): void {
  for (const entry of readdirSync(dir).sort()) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) walkFiles(root, path, output)
    else output.push(relative(root, path).split(sep).join("/"))
  }
}

export function inventoryAuthoringPaths(root: string): ReadonlyArray<string> {
  const output: Array<string> = []
  walkFiles(root, repoPath(root, "SoT"), output)
  return output.sort()
}

export interface GeneratedState {
  readonly module: string
  readonly launcher: string
}

export function expectedGeneratedState(root: string): GeneratedState {
  return {
    module: generatedModule(root),
    launcher: generatedLauncher(root)
  }
}

export function staleGeneratedPaths(root: string): ReadonlyArray<string> {
  const expected = expectedGeneratedState(root)
  const modulePath = repoPath(root, GENERATED_MODULE)
  const launcherPath = repoPath(root, LAUNCHER)
  const stale: Array<string> = []
  if (!existsSync(modulePath) || readFileSync(modulePath, "utf8") !== expected.module) stale.push(GENERATED_MODULE)
  if (readFileSync(launcherPath, "utf8") !== expected.launcher) stale.push(LAUNCHER)
  return stale
}

function writeGenerated(root: string): void {
  const expected = expectedGeneratedState(root)
  const modulePath = repoPath(root, GENERATED_MODULE)
  mkdirSync(dirname(modulePath), { recursive: true })
  writeFileSync(modulePath, expected.module)
  writeFileSync(repoPath(root, LAUNCHER), expected.launcher)
}

interface CliOptions {
  readonly check: boolean
  readonly root: string
}

function parseCli(argv: ReadonlyArray<string>): CliOptions {
  let check = false
  let root = resolve(import.meta.dirname, "..", "..")
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === "--check") check = true
    else if (arg === "--source-root") {
      const value = argv[index + 1]
      if (value === undefined) throw new Error("--source-root requires a path")
      root = resolve(value)
      index += 1
    } else {
      throw new Error(`Unknown argument: ${arg}`)
    }
  }
  return { check, root }
}

function main(argv: ReadonlyArray<string>): number {
  const options = parseCli(argv)
  if (!options.check) {
    writeGenerated(options.root)
    return 0
  }
  const stale = staleGeneratedPaths(options.root)
  for (const path of stale) console.error(`generated payload is stale: ${path}`)
  return stale.length === 0 ? 0 : 1
}

if (import.meta.main) {
  try {
    process.exit(main(process.argv.slice(2)))
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}
